function [N, modij, B1, B2] = lobatto_calcShapeFunctions(nita, p, iel, supel, local)
	[N,shapelq,dhdnitalq,Nder] = lobatto( 	nita, p(iel));%row-vectors
	[modij, invmodij] = sbfemodijcirlipa( 	supel(1).nnel, ...
											supel(1).centrecoord(iel).coord, ...
											shapelq, ...
											dhdnitalq, ...
											local(iel).xcrd, ...
											local(iel).ycrd);   
	[b1, b2, B1, B2] = sbfederiv2(supel(1).nnel, shapelq, dhdnitalq, invmodij);
end